(deftheme zenburn-test
  "Created 2017-10-01.")

(custom-theme-set-variables
 'zenburn-test
 '(ansi-color-names-vector ["#3f3f3f" "#cc9393" "#7f9f7f" "#f0dfaf" "#8cd0d3" "#dc8cc3" "#93e0e3" "#dcdccc"]))

(custom-theme-set-faces
 'zenburn-test
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#f0dfaf" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#d0bf8f" :underline t :weight normal))))
 '(cursor ((((class color) (min-colors 89)) (:background "green"))))
 '(escape-glyph ((t (:foreground "#f0dfaf" :bold t))))
 '(fringe ((((class color) (min-colors 89)) (:background "black"))))
 '(header-line ((t (:foreground "#f0dfaf" :background "#2b2b2b" :box (:line-width -1 :style released-button)))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight normal :foreground "LightSkyBlue"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(compilation-mode-line-fail ((t (:foreground "#cc9393" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#f0dfaf" :weight bold))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(isearch-fail ((t (:foreground "#dcdccc" :background "#8c5353"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(menu ((t (:foreground "#dcdccc" :background "#3f3f3f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(secondary-selection ((t (:background "#5f5f5f"))))
 '(trailing-whitespace ((t (:background "#cc9393"))))
 '(vertical-border ((t (:foreground "#dcdccc"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-negation-char-face ((t (:foreground "#dcdccc"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(font-lock-warning-face ((t (:foreground "#d0bf8f" :weight bold))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(ac-candidate-face ((t (:background "#6f6f6f" :foreground "black"))))
 '(ac-selection-face ((t (:background "#4c7073" :foreground "#dcdccc"))))
 '(popup-tip-face ((t (:background "#d0bf8f" :foreground "black"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#366060"))))
 '(popup-scroll-bar-background-face ((t (:background "#2b2b2b"))))
 '(popup-isearch-match ((t (:background "#3f3f3f" :foreground "#dcdccc"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#bfebbf" :background nil)) (t (:foreground "#5f7f5f" :background nil))))
 '(diff-changed ((t (:foreground "#f0dfaf"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#cc9393" :background nil)) (t (:foreground "#9c6363" :background nil))))
 '(diff-refine-added ((t :inherit diff-added :weight bold)))
 '(diff-refine-changed ((((class color) (min-colors 89)) (:background "skyblue4"))))
 '(diff-refine-removed ((t :inherit diff-removed :weight bold)))
 '(diff-header ((((class color) (min-colors 89)) (:background "grey45"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "grey60"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:background nil :underline "red"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:background nil :underline "magenta3"))))
 '(helm-header ((t (:foreground "#7f9f7f" :background "#3f3f3f" :underline nil :box nil))))
 '(helm-source-header ((t (:foreground "#f0dfaf" :background "#2b2b2b" :underline nil :weight bold :box (:line-width -1 :style released-button)))))
 '(helm-selection ((t (:background "#4f4f4f" :underline nil))))
 '(helm-selection-line ((t (:background "#4f4f4f"))))
 '(helm-visible-mark ((t (:foreground "#3f3f3f" :background "#d0bf8f"))))
 '(helm-candidate-number ((t (:foreground "#bfebbf" :background "#2b2b2b"))))
 '(helm-ff-directory ((t (:foreground "#dc8cc3"))))
 '(linum ((t (:foreground "#9fc59f" :background "#3f3f3f"))))
 '(message-cited-text ((t (:inherit font-lock-comment))))
 '(message-header-name ((t (:foreground "#8fb28f"))))
 '(message-header-other ((t (:foreground "#7f9f7f"))))
 '(message-header-to ((t (:foreground "#f0dfaf" :weight bold))))
 '(message-header-cc ((t (:foreground "#f0dfaf" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#f0dfaf" :weight bold))))
 '(message-header-subject ((t (:foreground "#dfaf8f" :weight bold))))
 '(message-header-xheader ((t (:foreground "#7f9f7f"))))
 '(message-mml ((t (:foreground "#f0dfaf" :weight bold))))
 '(message-separator ((t (:inherit font-lock-comment))))
 '(org-agenda-date-today ((t (:foreground "white" :slant italic :weight bold))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-archived ((t (:foreground "#dcdccc" :weight bold))))
 '(org-checkbox ((t (:background "#5f5f5f" :foreground "white" :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:foreground "#8cd0d3" :underline t))))
 '(org-done ((t (:bold t :weight bold :foreground "#afd8af"))))
 '(org-formula ((t (:foreground "#d0bf8f"))))
 '(org-headline-done ((t (:foreground "#afd8af"))))
 '(org-hide ((t (:foreground "#2b2b2b"))))
 '(org-level-1 ((t (:foreground "#dfaf8f"))))
 '(org-level-2 ((t (:foreground "#bfebbf"))))
 '(org-level-3 ((t (:foreground "#7cb8bb"))))
 '(org-level-4 ((t (:foreground "#d0bf8f"))))
 '(org-level-5 ((t (:foreground "#93e0e3"))))
 '(org-level-6 ((t (:foreground "#9fc59f"))))
 '(org-level-7 ((t (:foreground "#8c5353"))))
 '(org-level-8 ((t (:foreground "#4c7073"))))
 '(org-link ((t (:foreground "#d0bf8f" :underline t))))
 '(org-scheduled ((t (:foreground "#bfebbf"))))
 '(org-scheduled-previously ((t (:foreground "#8c5353"))))
 '(org-scheduled-today ((t (:foreground "#94bff3"))))
 '(org-special-keyword ((t (:foreground "#656555" :weight normal))))
 '(org-table ((t (:foreground "#9fc59f"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-time-grid ((t (:foreground "#dfaf8f"))))
 '(org-todo ((t (:bold t :foreground "#cc9393" :weight bold))))
 '(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 '(org-warning ((t (:bold t :foreground "#cc9393" :weight bold :underline nil))))
 '(org-column ((t (:background "#2b2b2b"))))
 '(org-column-title ((t (:background "#2b2b2b" :underline t :weight bold))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "SkyBlue1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "LightSteelBlue1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "turquoise2"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "aquamarine1"))))
 '(outline-6 ((t (:foreground "#9fc59f"))))
 '(outline-7 ((t (:foreground "#8c5353"))))
 '(outline-8 ((t (:foreground "#4c7073"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "red1" :foreground "white"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "dodgerblue1" :foreground "white"))))
 '(default ((((class color) (min-colors 89)) (:background "#181a26" :foreground "gray80"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.728))))
 '(info-title-2 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.44))))
 '(info-title-3 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.2))))
 '(info-title-4 ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "Red1"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "seashell4"))))
 '(diff-function ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-index ((((class color) (min-colors 89)) (:inherit diff-file-header))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "white" :background "darkolivegreen"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "white" :background "dodgerblue4"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "white" :background "indianred4"))))
 '(dired-marked ((((class color) (min-colors 89)) (:background "dodgerblue3" :foreground "white"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2")))))

(provide-theme 'zenburn-test)
